### ISSUE TITLE
Unable to upload plants in Plants Project

### ISSUE THREAD

**Issue by prashantmrshine** [ServiceNowDevProgram/Plants#305]
Unable to upload plants in Plants Project under My Plants

**Comment by Paulsylo25** [comment]
May I know what the error is? if you do not see any option to upload then You can go to table - x_snc_plant_mgmt_plants and change the view to "Quick Details" You can see this option to add images.

**Comment by Paulsylo25** [comment]
https://yourinstance/now/nav/ui/classic/params/target/x_snc_plant_mgmt_plants.do%3Fsys_id%3D-1%26sys_is_list%3Dtrue%26sys_target%3Dx_snc_plant_mgmt_plants%26sysparm_checked_items%3D%26sysparm_fixed_query%3D%26sysparm_group_sort%3D%26sysparm_list_css%3D%26sysparm_query%3D%26sysparm_referring_url%3Dx_snc_plant_mgmt_plants_list.do%26sysparm_target%3D%26sysparm_view%3DQuick_Details

**Comment by Paulsylo25** [comment]
@prashantmrshine hope this fix the issue
