### ISSUE TITLE
Plants does not show up in plants landing page

### ISSUE THREAD

**Issue by mmaraj1** [ServiceNowDevProgram/Plants#70]
I can see that there are plants on my plants table, but nothing show up on the plants landing page
<img width="832" alt="myplants landing page" src="https://github.com/ServiceNowDevProgram/Plants/assets/41468936/c4a28679-b3de-4f7e-9687-a4c0d7802b1e">
<img width="670" alt="myplants" src="https://github.com/ServiceNowDevProgram/Plants/assets/41468936/392298a1-14c3-41db-bb55-293d5d0da4cc">

**Comment by paigesndev** [comment]
I've created a new portal, but it is intentionally pretty sparse. This will give individuals the opportunity to add to it for the purposes of Hacktoberfest. As a reminder, new pull/merge requests should be submitted after October 1 to count towards the Hacktoberfest.
