### ISSUE TITLE
Add Knowledge for plants on the Portal

### ISSUE THREAD

**Issue by 404paige** [ServiceNowDevProgram/Plants#71]
Create a new KB and populate it? Source from the outside? You choose, but lets make it easy to access basic plant information from the Plants portal.

**Comment by noviicee** [comment]
Hi @paigesndev ! Can I try this..?

**Comment by paigesndev** [comment]
@noviicee - Apologies! I didn't see your comment. Please feel free to just do any of the issues/enhancements listed. No need to ask!
