### ISSUE TITLE
What tasks do I have to do?

### ISSUE THREAD

**Issue by 404paige** [ServiceNowDevProgram/Plants#74]
My tasks are already auto-generated for me, but now I should be able to see those To Dos on the portal (even better if I can check them off...)

**Comment by hentonjd** [comment]
I'd like to take this one. Can it be assigned to me?

**Comment by hentonjd** [comment]
May have to go back to the drawing board on this one. I suspect that I’ll need to add an “assigned to” field on the x_snc_plants_db_tasks table. Otherwise how would plant tasks show under someone’s my tasks list? Am I on the right track?

**Comment by JonSandoval** [comment]
Submitted pull request to address this:  Show My Tasks for Plants App #176
